export const INITIAL_LOAD = "INITIAL_LOAD";
export const SET_OPTION_MAIN_VENUE = "SET_OPTION_MAIN_VENUE";
export const SET_OPTION_STAFF_TYPES = "SET_OPTION_STAFF_TYPES";
export const SET_OPTION_PAY_RATES = "SET_OPTION_PAY_RATES";
export const GET_OPTION = "GET_OPTION";
export const EDIT_EMPLOYMENT_DETAILS = "EDIT_EMPLOYMENT_DETAILS";
